# docker-compose.yml
version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://logisticdevuser:adfgERC@27.74.255.96:8000/meulogisticdev
    depends_on:
      - mongo

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"